name: Build and Deploy UserIdentityApplication

on:
  push:
    branches: [ "main" ]  # Trigger on push to the main branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      Solution_Name: UserIdentityApplication.sln  # Your solution file name
      Project_Path: ./UserIdentityApplication/UserIdentityApplication.csproj  # Path to your main project file
      Configuration: Release  # Build configuration (Release or Debug)

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # Use the .NET 8 SDK

    - name: Restore Dependencies
      run: dotnet restore ${{ env.Project_Path }}

    - name: Build Application
      run: dotnet build ${{ env.Project_Path }} --configuration ${{ env.Configuration }} --no-restore

    - name: Run Tests
      run: dotnet test ${{ env.Solution_Name }} --configuration ${{ env.Configuration }} --no-restore --verbosity normal

    - name: Publish Application
      run: dotnet publish ${{ env.Project_Path }} --configuration ${{ env.Configuration }} --output ./publish

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Published_App
        path: ./publish
